### ISSUE TITLE
New versioning format breaks cpanm

### ISSUE THREAD

**Issue by DrHyde** [chocolateboy/autobox#13] opened 2018-05-31 11:07 UTC
We have this in the `cpanfile` for my project at work:

    requires 'autobox', '>= 2.86';

Since 3.0.1 came out that's started to break:

    Argument "^C\0^A" isn't numeric in numeric ge (>=) at ...

Pleeeeeease switch back to using numbers for versions, nothing else works reliably (yes, I'm going to report this as a bug against version.pm as well).

**Comment by DrHyde** [comment] 2018-05-31 11:12
See also https://rt.cpan.org/Ticket/Display.html?id=125441

**Comment by chocolateboy** [comment] 2018-05-31 21:14
cc @Grinnz

**Comment by Grinnz** [comment] 2018-05-31 23:29
That doesn't make sense. A version object will compare fine with a number.

**Comment by Grinnz** [comment] 2018-05-31 23:30
What version of Perl and version.pm are you using?

**Comment by JohnPeacock** [comment] 2018-06-01 01:00
Why isn't this a bug of cpanm?  This block in particular is many many many different flavors of wrong:
`          my $action  = $local && !$reinstall
                      ? $self->numify_ver($version) < $self->numify_ver($local)
                          ? "downgraded"
                          : "upgraded"
                      : undef;
  `

**Comment by JohnPeacock** [comment] 2018-06-01 01:18
ticket opened with App-cpanminus: https://github.com/miyagawa/cpanminus/issues/574

**Comment by Grinnz** [comment] 2018-06-01 01:52
Side note: a more common way to write `requires 'autobox', '>= 2.86';` would be `requires 'autobox', '2.86';` (version ranges are greater-than-or-equals by default).

**Comment by miyagawa** [comment] 2018-06-01 03:07
I suggest closing this issue since it has nothing to do with the autobox's versioning scheme, and move to https://github.com/miyagawa/cpanminus/issues/574 although i can't reproduce with the combination of cpanm, perl and version.pm that i have.

**Comment by chocolateboy** [comment] 2018-06-04 17:12
Closing this as I can't reproduce it without more information on where the error occurs.

@DrHyde if you have more details, please provide them and I'll take another look.

**Closed by chocolateboy** 2018-06-04 17:12 UTC
Labels: compatibility
